version: '3.7'

services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 300
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes: 
      - /data/db
  client:
    container_name: client
    restart: always
    build: 
      context: ./frontend/kanban
    command: npm run serve
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 300
    ports:
      - '8080:8080'
    volumes:
      - './frontend/kanban:/client'
      - '/client/node_modules'