version: '3'

services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  client:
    container_name: client
    build: ./frontend/kanban
    ports:
      - 8080:8080
    volumes:
      - ${PWD-.}/client:/usr/src/app
      - /usr/src/app/node_modules