version: '3.7'

services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 300
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  client:
    container_name: client
    #restart: always
    build: 
      context: ./frontend/kanban
    command: npm run serve
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 300
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      #- ./frontend/kanban/src:/usr/src/client
      - /usr/src/client/node_modules:cached